const users = [{
    name: 'Karen',
    messages: 0,
    writing: false,
    lastMessage: 'Call me, now',
    phoneNumber: '+1212332223',
    lastMassageTime: '00:20',
    pinned: true,
    photo: 'images/photos/karen.jpg',
    online: true,
    username: 'doyouneedhelp',
    bio: 'Doctor',
    lastSeen: 'online',
    muted: false
}, {
    name: 'Jack Russel',
    messages: 0,
    writing: false,
    lastMessage: 'I`ll try',
    lastMassageTime: '00:20',
    phoneNumber: '+91119111911',
    pinned: true,
    username: 'bite-bite',
    bio: 'The dog',
    photo: 'images/photos/jack_russel.jpg',
    lastSeen: 'last seen a long time ago',
    online: false,
    muted: false
}, {
    name: 'Celine Dion',
    messages: 2,
    writing: false,
    lastMessage: 'To win',
    lastMassageTime: '00:20',
    phoneNumber: '+380123456789',
    pinned: false,
    photo: 'images/photos/celine_dion.jpeg',
    online: false,
    username: 'Celine',
    bio: 'Singer',
    lastSeen: 'last seen 12 minutes ago',
    muted: false
}, {
    name: 'Bred Pitt',
    messages: 2,
    writing: false,
    lastMessage: 'with missed',
    lastMassageTime: '00:20',
    phoneNumber: '+9876553231',
    pinned: false,
    photo: 'images/photos/bred_pitt.jpg',
    online: false,
    username: 'BredPitt',
    bio: 'Actor',
    lastSeen: 'last seen recently',
    muted: true
}, {
    name: 'Sylvester Stallone',
    messages: 2,
    writing: false,
    lastMessage: 'part of',
    lastMassageTime: '00:20',
    phoneNumber: '+8933223322',
    pinned: false,
    photo: 'images/photos/sylvester_stallone.jpg',
    online: true,
    lastSeen: 'Online',
    username: 'Online',
    bio: 'Actor',
    muted: false
}, {
    name: 'Arnold Schwarzenegger',
    typing: true,
    messages: 2,
    writing: false,
    lastMessage: 'Hi',
    lastMassageTime: '00:20',
    username: 'Online',
    bio: 'Actor',
    phoneNumber: '+380123456789',
    lastSeen: 'Never',
    pinned: false,
    photo: 'images/photos/arnold_schwarzenegger.jpg',
    online: false,
    muted: true
}];

export default users;
